[build-system]
requires = ["setuptools>=80.0"]
build-backend = "setuptools.build_meta"

[project]
name = "simple-http-checker"
version = "0.1.0"
description = "A simple tool to check the status of any http URL."  
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.28,<3.0",
    "click>=8.0,<9.0"
]

[project.optional-dependencies]
dev = [
    "ruff",
    "black"
]

[project.scripts]
check-urls = "simple_http_checker.cli:main"

[tool.ruff]
line-length = 65

[tool.black]
line-length = 55